task :default => :build

task :build do
  puts "build"
end

task :get do
  require 'pit'
  TWITTER_CONFIG = Pit.get('twitter.com')
  puts "get twitter data"
  `curl https://stream.twitter.com/1/statuses/filter.json?track="itunes" -u#{TWITTER_CONFIG['user']}:#{TWITTER_CONFIG['pass']} | mongoimport -d twitter -c in`
end

task :count_itunes do
  puts "counting"
  `hadoop jar hadoop/mongo-hadoop-streaming-assembly*.jar -mapper hadoop/mapper_itunes_url.rb -reducer hadoop/reducer.rb -inputURI mongodb://127.0.0.1/twitter.itunes -outputURI mongodb://127.0.0.1/twitter.itunes_app`
end
